# Generated by Django 5.1.3 on 2025-01-20 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatchikVesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("tekushchaya_nagruzka", models.FloatField()),
                ("summarnii_ves_za_period", models.FloatField()),
                ("min_ves_za_period", models.FloatField()),
                ("max_ves_za_period", models.FloatField()),
                ("srednii_ves_reisa_za_period", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Probeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("probeg_na_segodnya", models.FloatField()),
                ("probeg_za_period", models.FloatField()),
                ("kolichestvo_reisov", models.FloatField()),
                ("kolichestvo_poezdok_za_period", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Shini",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("davlenie_v_shinah", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Toplivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("ostatok_na_tekushchii_moment", models.FloatField()),
                ("raskhod_za_period", models.FloatField()),
                ("raskhod_za_poezdku", models.FloatField()),
                ("raskhod_na_khkh_za_period", models.FloatField()),
                ("raskhod_pod_nagruzkoi_za_period", models.FloatField()),
                ("raskhod_v_puti_za_period", models.FloatField()),
                ("raskhod_privedennii_g_t_km_za_period", models.FloatField()),
                ("raskhod_privedennii_g_t_km_obshchii", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Vremya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("vremya_s_nachala_perioda", models.FloatField()),
                ("vremya_raboty_dvigatelya_za_period", models.FloatField()),
                ("vremya_hkh_za_period", models.FloatField()),
                ("motochasy_obshchie", models.FloatField()),
                ("motochasy_za_period", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Jsession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jsession", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jsession",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_password", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_password",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("id_car", models.CharField(max_length=255, unique=True)),
                (
                    "account_name",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи",
                    ),
                ),
                (
                    "datchik_vesa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.datchikvesa",
                        verbose_name="Датчик веса",
                    ),
                ),
                (
                    "probeg",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.probeg",
                        verbose_name="Пробег",
                    ),
                ),
                (
                    "shini",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.shini",
                        verbose_name="Давление в шинах",
                    ),
                ),
                (
                    "toplivo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.toplivo",
                        verbose_name="Топливо",
                    ),
                ),
                (
                    "vremya",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.vremya",
                        verbose_name="Время",
                    ),
                ),
            ],
            options={
                "verbose_name": "car",
                "verbose_name_plural": "cars",
            },
        ),
    ]
