# Generated by Django 5.1.3 on 2025-02-18 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_car",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Идентификатор машины"
                    ),
                ),
                (
                    "account_name",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Машина",
                "verbose_name_plural": "Машины",
            },
        ),
        migrations.CreateModel(
            name="Jsession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jsession", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jsession",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_reisov",
                    models.IntegerField(default=1, verbose_name="План по рейсам"),
                ),
                (
                    "plan_ves_za_period",
                    models.IntegerField(
                        default=1, verbose_name="План по тоннам (весу)"
                    ),
                ),
                (
                    "account_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmenaOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.TimeField(
                        default="08:00", verbose_name="Начало первой смены"
                    ),
                ),
                (
                    "end",
                    models.TimeField(
                        default="16:00", verbose_name="Окончание первой смены"
                    ),
                ),
                (
                    "account_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Первая смена",
            },
        ),
        migrations.CreateModel(
            name="UserPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_password", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_password",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dt",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата и время"
                    ),
                ),
                (
                    "ostatok_na_tekushchii_moment",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Остаток на текущий момент"
                    ),
                ),
                (
                    "raskhod_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Расход за период"
                    ),
                ),
                (
                    "raskhod_za_poezdku",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Расход за поездку"
                    ),
                ),
                (
                    "raskhod_na_khkh_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Расход на ХХ за период"
                    ),
                ),
                (
                    "raskhod_pod_nagruzkoi_za_period",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Расход под нагрузкой за период",
                    ),
                ),
                (
                    "raskhod_v_puti_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Расход в пути за период"
                    ),
                ),
                (
                    "raskhod_privedennii_g_t_km_za_period",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Приведенный расход г/т*км за период",
                    ),
                ),
                (
                    "raskhod_privedennii_g_t_km_obshchii",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Общий приведенный расход г/т*км",
                    ),
                ),
                (
                    "tekushchaya_nagruzka",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Текущая нагрузка"
                    ),
                ),
                (
                    "summarnii_ves_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Суммарный вес за период"
                    ),
                ),
                (
                    "min_ves_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Минимальный вес за период"
                    ),
                ),
                (
                    "max_ves_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Максимальный вес за период"
                    ),
                ),
                (
                    "srednii_ves_reisa_za_period",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Средний вес рейса за период",
                    ),
                ),
                (
                    "probeg_na_segodnya",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Пробег на сегодня"
                    ),
                ),
                (
                    "probeg_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Пробег за период"
                    ),
                ),
                (
                    "kolichestvo_reisov",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Количество рейсов"
                    ),
                ),
                (
                    "kolichestvo_poezdok_za_period",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Количество поездок за период",
                    ),
                ),
                (
                    "vremya_s_nachala_perioda",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Время с начала периода"
                    ),
                ),
                (
                    "vremya_raboty_dvigatelya_za_period",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Время работы двигателя за период",
                    ),
                ),
                (
                    "vremya_hkh_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Время ХХ за период"
                    ),
                ),
                (
                    "motochasy_obshchie",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Моточасы общие"
                    ),
                ),
                (
                    "motochasy_za_period",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Моточасы за период"
                    ),
                ),
                (
                    "davlenie_v_shinah",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Давление в шинах"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_data",
                        to="cars.cars",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневные данные",
                "verbose_name_plural": "Ежедневные данные",
                "unique_together": {("car", "dt")},
            },
        ),
    ]
