# Generated by Django 5.1.3 on 2024-12-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="flight",
            field=models.IntegerField(default=20, verbose_name="Рейсы"),
            preserve_default=False,
        ),
    ]
