# Generated by Django 5.1.3 on 2025-01-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="datchik_vesa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="cars.datchikvesa",
                verbose_name="Датчик веса",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="probeg",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="cars.probeg",
                verbose_name="Пробег",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="shini",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="cars.shini",
                verbose_name="Давление в шинах",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="toplivo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="cars.toplivo",
                verbose_name="Топливо",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="vremya",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="cars.vremya",
                verbose_name="Время",
            ),
        ),
    ]
