# Generated by Django 5.1.3 on 2025-02-24 17:10

import django.db.models.deletion
from django.db import migrations, models


def work_shift_set(apps, schema_editor):
    DailyData = apps.get_model("cars", "DailyData")
    WorkShift = apps.get_model("cars", "WorkShift")

    def get_shift_name(dt):
        if 8 <= dt.hour < 16:
            return "C1"
        elif 16 <= dt.hour:
            return "C2"
        else:
            return "C3"

    for daily_data in DailyData.objects.filter(work_shift__isnull=True):
        work_shift = WorkShift()
        work_shift.daily_data_id = daily_data.id
        work_shift.work_shift_name = get_shift_name(daily_data.dt)
        work_shift.save()


def reverse_work_shift_set(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_shift_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Смена",
                    ),
                ),
                (
                    "daily_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_shift",
                        to="cars.dailydata",
                    ),
                ),
            ],
        ),
        migrations.RunPython(work_shift_set, reverse_work_shift_set),
    ]
