# Generated by Django 5.1.3 on 2025-03-06 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_workshift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "select_smena",
                    models.CharField(
                        choices=[
                            ("smena_one", "smena_one"),
                            ("smena_two", "smena_two"),
                            ("smena_three", "smena_three"),
                            ("all", "all"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Выбранная смена",
                    ),
                ),
                (
                    "account_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
