# Generated by Django 5.1.3 on 2025-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_cars_datchik_vesa_alter_cars_probeg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="id_car",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
