# Generated by Django 5.1.3 on 2025-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_smenaall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smenaall",
            name="end",
            field=models.IntegerField(
                default=24, verbose_name="Окончание смены (часы)"
            ),
        ),
    ]
